name: dialog

on:
  push:
    branches: [ developers/lonycell/master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Stop Server (dialog_server)
        run: |
          pm2 stop dialog_server
          pm2 delete dialog_server
        continue-on-error: true
    
      - name: Check version
        run: |
          node -v
          npm -v

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependency
        run: npm ci --ignore-scripts
      
      - name: Register and start dialog_server to PM2
        run: |
          pm2 start "npm run start" --name dialog_server

      - name: Check PM2 status
        run: pm2 status